spring:
  application:
    name: ${APPLICATION_NAME}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: ${DATABASE_DIALECT}
    hibernate:
        ddl-auto: ${HIBERNATE_DDL_AUTO}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION_MS}

frontend:
  url: ${FRONTEND_URL}