spring:
  application:
    name: shrinkit

  datasource:
    url: jdbc:mysql://localhost:3306/shrinkitdb
    username: root
    password: password

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
        ddl-auto: update

jwt:
  secret: GjR3bDdAbPnwM7Gs1gH8vFoyq3EcfGeXLxnN6bxNpeinHOg1GtGTERQoq9PLUUZ9
  expiration: 172800000 # 20 days in milliseconds